apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: bluesky-app
  name: bluesky-app
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bluesky-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bluesky-app
    spec:
      containers:
        - image: enpapex/bluesky-react-sample-app:sha-2f94a1b
          imagePullPolicy: IfNotPresent
          name: bluesky-app
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
kind: Service
apiVersion: v1
metadata:
  name: bluesky-app-service
  namespace: default
spec:
  selector:
    app: bluesky-app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      name: http
      protocol: TCP
